export const SUCCESS_RESPONSE = {
  createdSuccessfully: "Post created successfully",
  postFetched: "Post fetched successfully",
  userPostFetched: "User post fetched successfully",
  postUpdatedSuccessfully: "Post updated successfully",
  postDeletedSuccessfully: "Post deleted successfully",
  otpSent: "OTP sent successfully",
  otpVerified: "OTP verified successfully",
  socialLogin: "Social login successful",
  mobileOtpSent: "OTP sent to registered mobile number",
  loginSuccessful: "Login successful",
  userRegistered: "User registered",
  likeSuccessful: "Liked successfully",
  unlikeSuccessful: "Unliked successfully",
  commentAdded: "Comment added successfully",
  commentUpdated: "Comment updated successfully",
  commentDeleted: "Comment deleted successfully",
  commentsFetched: "Comments fetched successfully",
  petAdded: "Pet added successfully",
  petUpdated: "Pet updated successfully",
  petDeleted: "Pet deleted successfully",
  petsFetched: "Pets fetched successfully",
};

export const ERROR_RESPONSE = {
  fileUploadError: "Only image and video files are allowed",
  postNotFound: "Post not found",
  commentNotFound: "Comment not found",
  passwordNotMatched: "Passwords do not match",
  emailAlreadyExists: "Email already exists",
  usernameAlreadyExists: "Username already taken",
  emailRequired: "Email is required",
  userNotFound: "User not found",
  emailOtpRequired: "Email and OTP required",
  invalidOtp: "Invalid OTP",
  otpExpired: "OTP expired",
  userSignup: "User not found, please sign up",
  invalidLogin: "Invalid login type",
  emailNotVerified: "Email is not verified",
  invalidCredentials: "Invalid credentials",
  emailSignup: "Email not found, please sign up",
  invalidEntityType: "Invalid entity type",
  missingEntityInfo: "Entity ID and type are required",
  unauthorized: "Unauthorized user",
  unauthorizedAction: "Unauthorized to perform this action",
  invalidInput: "Invalid input",
  cannotEditAfter24h: "Cannot edit comment after 24 hours",
  postIdRequired: "Post ID is required",
  commentIdRequired: "Comment ID is required",
  petNotFound: "Pet not found",
  noPetsFound: "No pets found for this user",
  missingRequiredFields: "Some required fields are missing",
};
